### ISSUE TITLE
troubleshoot headers are not installed

### ISSUE THREAD

**Issue by abouvier** [Elv13/libringqt#3]
`<troubleshoot/dispatcher.h>` required by ring-kde is not installed by libringqt because `libringqt_troubleshoot_LIB_HDRS` is not set in `CMakeLists.txt`

e.g.:
```
SET(libringqt_troubleshoot_LIB_HDRS
  src/troubleshoot/*.h
)
```

**Comment by Elv13** [comment]
whoops, sorry about this, I should have been more careful. My continuous integration system that build the nighlies somehow had managed to find the header... I should make it a bit more strict.

Just curious, so you installed libringqt on your system instead of just letting ring-kde fetch it or copy/paste the code in path/to/ring-kde/? Is there is reason why or is it "just because I did it that way"? The main issue is that `libringqt` API is currently undergoing quite a lot of changes to extend it's scope and trying to package it isn't really such a good idea given only the latest ring-kde commit and libringqt are compatible with each other. Of course, the idea is to stabilize the API, but it can only be done once the scope stops expending.

Beside that, so you use Ring-KDE? How well does it works for you? Any bugs or pain points you want me to address? As you probably noticed, it is undergoing heavy, heavy development and not all commits are ultra stable right now, but it's on the home stretch, 3.0 (final) is expected soon (but I said that before and was then asked to implement more things...).

**Comment by abouvier** [comment]
Désolé, mais je vais répondre en français. Je prie pour que tu sois réellement québécois :p

J'ai installé libringqt et ring-kde séparément parce que je n'ai pas réussi à compiler ring-kde lorsqu'il s'occupe de télécharger lui-même libringqt. Aussi parce que c'était plus propre de créer deux paquets pour l'installation sur Arch Linux en passant par l'AUR ([libringqt-git](https://aur.archlinux.org/packages/libringqt-git/) et [ring-kde-git](https://aur.archlinux.org/packages/ring-kde-git/)). Cela ne change pas grand chose non plus parce que la version téléchargée par le CMakeLists.txt de ring-kde, et celle récupérée en installant le paquet libringqt-git sont de toute façon basées sur le dernier commit de la branche master (pareil pour ring-kde-git). Je suis donc toujours en train d'utiliser la dernière version des deux paquets.

Sinon je n'utilise pas encore la partie ring de ring-kde. Je cherchais un logiciel Qt pour remplacer Linphone comme client SIP. Et même pour cette partie là, je n'ai pas encore tout testé. J'arrive à recevoir des appels, mais pas à en émettre. Il y a aussi des bugs dans l'interface de gestion de compte/profil. Les informations que je rentre dans les champs de texte ne sont pas sauvegardées une fois le formulaire enregistré. 

Ah aussi, le fichier d'en-tête `src/troubleshoot/base.h` est également requis pour que ring-kde compile correctement :p

**Comment by Elv13** [comment]
> Il y a aussi des bugs dans l'interface de gestion de compte/profil

Oui, plusieurs. Mon Boss s'en fou pas mal et doesn't care much about SIP. Je l'utilise personnellement avec VoIP.ms et ca "marche" en modifiant les settings suffisamment. Un jour je vais porter le code en QML, mais pour l'instant je vais regler le bug du profil et laisser ca comme ca. J'en ai deja par dessus la tete avec les bugs normaux pour toucher a du deprecated code. Mais n'ait pas peur, SIP est important pour moi et je le test. Je l'utilise comme telephone. C'est juste que je peux pas justifier les heures necessaire pour tout remetre aussi bien que l'ancien SFLPhone quand il y a des bogues plus important a regler (et il y en a *beaucoup*, 3.0 est un full rewrite d'un projet qui avais 13 ans de bugfixes, don't expect miracles)

> Les informations que je rentre dans les champs de texte ne sont pas sauvegardées une fois le formulaire enregistré.

C'est un changement recent qui cause ca. J'avais pas vraiment le choix de "tout changer" car la detection des media ne supportait pas bien quand il y a plusieurs compte SIP et Ring en meme temps. Quand cela arrivait, les bouton "appel" et "chat" étaient non accessible et l'application devenait innutile. C'est mieux pour l'instant de ce concentrer pour eviter les false positive que d'ajouter des feature que 1% des utilisateur utilisent.

Et tout les trucs avec le "toubleshoot" vont aider a regler des problemes comme la perte de reseau pendant un appel, un jitter instable ou un round-trip-time de packets SIP/RTP qui fait exploser la latence. Mais ca va prendre encore au moins une semaine a ce stabiliser. C'est dans la branche master parce que mon Boss pense que je fais rien si c'est pas dans les nighlies...

Sinon il utilise trop de CPU, trop de RAM, trop de I/O, etc, etc. Mais comme j'ai dit pour l'instant la priorite c'est de fixer le "common use case" et de faire un release. Meme si je brise 10 autre features pour y arriver. *Make it work, make it work great, make it work fast*.

**Comment by Elv13** [comment]
Both the second header and the profile issue have been fixed
